databases:
  - name: courtiq-db
    plan: free
    databaseName: courtiq
    user: courtiq_user

services:
  - type: web
    name: courtiq
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: DATABASE_URL
        fromDatabase:
          name: courtiq-db
          property: connectionString
